package com.modernmusicplayer.app.databinding

// Auto-generated by Android Data Binding
// This file should be generated automatically when you build the project
// If you see errors related to databinding, try:
// 1. Build > Clean Project
// 2. Build > Rebuild Project
// 3. File > Invalidate Caches / Restart

// The actual binding classes will be generated based on your XML layouts:
// - ActivityMainBinding (from activity_main.xml)
// - ActivityAuthBinding (from activity_auth.xml)
// - FragmentPlayerBinding (from fragment_player.xml)
// - FragmentHomeBinding (from fragment_home.xml)
// - ItemSongBinding (from item_song.xml)
// - ItemSongHorizontalBinding (from item_song_horizontal.xml)
